/**
 * Portfolio content, extracted from the raw material in ../NeededData.
 *
 * Every field below is traceable to a file in that folder. Nothing is invented; where the source
 * is silent the field is left empty and the assumption is documented next to the entry.
 *
 * Sources
 *   cv_extracted.txt / Mohamed_Walid_Abdullah_CV.pdf ... profile, education, experience, CV projects
 *   LomyLinkedInPost/LomyPostText.doc .................. Knowly (Django) project
 *   SunnyLandLinkedInPost/PostText.txt ................. Sunny Land (Unity) project
 *   Talabate LinkedIn Post/TalabatLinkedInPostText.doc . E-Commerce backend (LinkedIn post)
 *   Talabate LinkedIn Post/Talabat Backend Technical Report.md  same project, deep technical report
 *   LinkedIn Restaurand Post/ThePalatePostText.txt .... The Palate (restaurant platform)
 *   LinkedIn Restaurand Post/LinkedIn Report Resaurant WebSite.md  same project, technical report
 *   CompanyManagmentSystemLinkedInPostData/*.png ...... Company Management System (screenshots only;
 *                                                         the accompanying .doc is 0 bytes, so the
 *                                                         description is derived from the screens)
 *
 * Assumptions (also restated in the import report)
 *   A1  University dates are normalised to 2022-09-01 .. 2026-07-01 because the CV only gives years.
 *   A2  Route Academy dates are normalised to 2024-01-01 .. 2025-12-31 for the same reason.
 *   A3  profile.yearsOfExperience = 2 is derived from the Route Academy programme plus independent
 *       project work across the university years; the CV itself only says "recent graduate".
 *   A4  Project start/end dates are left empty: no source file states them, and guessing would put
 *       fabricated dates in the UI.
 *   A5  Knowly has no repository link anywhere in NeededData, so its githubUrl stays empty.
 *   A6  The Company Management System stack is inferred (ASP.NET Core + SQL Server) from its screens
 *       (users / roles / employees / departments / e-mail password reset) because its post text file
 *       is empty. Its technologies are limited to what that inference supports.
 *   A7  The Sunny Land links are the LinkedIn redirect short-links that the post publishes; they are
 *       stored verbatim because the post does not expose the underlying GitHub / Game Jolt URLs.
 *   A8  "E-Commerce Backend API" in the CV and the Talabat LinkedIn post / technical report are the
 *       same project (same solution name `E-Commerse.Web`, same Redis + Stripe + Onion stack), so
 *       they are merged into one record.
 *   A9  Video walkthroughs (.mp4) are attached to their own project gallery, which stores
 *       screenshots and recordings in the same record and renders each with the right element.
 *       The largest, CompanyManagmentSystem.mp4 (147 MiB), only fits now that the .mp4 ceiling is
 *       200 MB. LomyReview.mp4 is byte-identical to KnowlyWebsiteRecordVideo.mp4 (same SHA-256),
 *       so only the latter is imported and the gallery shows the clip once.
 */

export const TYPES = [
  { name: "Languages", description: "Programming languages I use across backend, scripting and game work" },
  { name: "Backend", description: "Server-side frameworks, APIs and data access" },
  { name: "Architecture", description: "How I structure a solution so it stays maintainable" },
  { name: "Database", description: "Relational modelling, schema design and persistence" },
  { name: "Frontend", description: "Browser-side frameworks and component architecture" },
  { name: "Game Development", description: "Engine tooling, gameplay systems and level design" },
  { name: "Tools", description: "Everyday developer tooling and documentation" },
];

export const SKILLS = [
  // Languages
  { name: "C#", types: ["Languages", "Backend"], description: "Primary language: ASP.NET Core APIs and Unity gameplay scripts" },
  { name: "SQL", types: ["Languages", "Database"], description: "Querying, stored procedures, views and indexing in SQL Server" },
  { name: "Python", types: ["Languages", "Backend"], description: "Used for the Django Knowly platform and scripting" },
  { name: "C++", types: ["Languages"], description: "Foundational language from the computer science curriculum" },

  // Backend
  { name: "ASP.NET Core Web API / MVC", types: ["Backend"], description: "Web APIs and MVC apps built on .NET 8" },
  { name: "RESTful API Design", types: ["Backend", "Architecture"], description: "Resource-oriented routes, correct verbs and consistent response envelopes" },
  { name: "Entity Framework Core", types: ["Backend", "Database"], description: "Code-First and Database-First, Fluent API, owned types and migrations" },
  { name: "LINQ", types: ["Backend"], description: "Query composition, deferred execution and specification-based predicates" },
  { name: "JWT Authentication", types: ["Backend"], description: "Stateless bearer tokens with role claims and refresh flows" },
  { name: "ASP.NET Core Identity", types: ["Backend", "Database"], description: "Password hashing, roles, lockout and a separate identity database" },
  { name: "SignalR", types: ["Backend"], description: "Real-time push notifications for admin dashboards" },
  { name: "Caching", types: ["Backend", "Tools"], description: "Redis plus a custom action-filter cache with per-user isolation" },
  { name: "Stripe Payments", types: ["Backend"], description: "PaymentIntent lifecycle with server-side amount verification" },
  { name: "Background Services", types: ["Backend"], description: "Hosted BackgroundService workers for scheduled synchronisation" },
  { name: "Reporting & Export", types: ["Backend", "Tools"], description: "Excel, PDF and CSV generation behind a single abstraction" },

  // Architecture
  { name: "Clean Architecture", types: ["Architecture"], description: "Strict dependency direction with the composition root in the web layer" },
  { name: "Onion / N-Tier Architecture", types: ["Architecture"], description: "Dependency inversion so inner layers never depend on outer ones" },
  { name: "Repository Pattern", types: ["Architecture"], description: "Generic repository over specifications, shared through one DbContext" },
  { name: "Unit of Work", types: ["Architecture"], description: "Atomic commits with dictionary-cached lazy repository creation" },
  { name: "Specification Pattern", types: ["Architecture"], description: "Composable query objects instead of scattered LINQ chains" },
  { name: "Dependency Injection", types: ["Architecture"], description: "Constructor injection, lazy factory delegates and service lifetimes" },
  { name: "SOLID Principles", types: ["Architecture"], description: "Single responsibility, open/closed, and interface segregation in practice" },
  { name: "Pagination", types: ["Architecture"], description: "Page index / page size on every collection endpoint" },
  { name: "Global Exception Handling", types: ["Architecture", "Backend"], description: "Domain exception hierarchy mapped to HTTP status codes by middleware" },

  // Database
  { name: "SQL Server", types: ["Database"], description: "Primary relational engine, including filtered unique indexes for business rules" },
  { name: "ERD Design", types: ["Database"], description: "Entity relationship diagrams before any code is written" },
  { name: "Schema Design", types: ["Database"], description: "Normalised schemas with owned value types and snapshot patterns" },
  { name: "Code-First", types: ["Database"], description: "Model-driven design with EF Core migrations" },
  { name: "Database-First", types: ["Database"], description: "Reverse engineering an existing database into the model" },
  { name: "Dual Database Design", types: ["Database", "Architecture"], description: "Application data and identity data kept in separate databases" },

  // Frontend
  { name: "React", types: ["Frontend"], description: "Component-based SPAs, code splitting and protected routes" },
  { name: "Tailwind CSS", types: ["Frontend"], description: "Utility-first styling for responsive, consistent interfaces" },
  { name: "Stripe Elements", types: ["Frontend", "Backend"], description: "Hosted payment fields so card data never touches the application server" },

  // Game development
  { name: "Unity", types: ["Game Development"], description: "Component-based engine workflow: GameObjects, prefabs, scenes and the editor" },
  { name: "2D Tilemaps & Physics", types: ["Game Development"], description: "Rigidbody2D, colliders, triggers and tilemap level design" },
  { name: "Animator & Audio", types: ["Game Development"], description: "Animation states, transitions, parameters and sound effects" },

  // Tools
  { name: "Git & GitHub", types: ["Tools"], description: "Version control, review history and repository organisation" },
  { name: "Swagger / OpenAPI", types: ["Tools", "Backend"], description: "Generated API documentation with structured validation responses" },
  { name: "Postman", types: ["Tools"], description: "Manual endpoint testing during development" },
  { name: "AutoMapper", types: ["Tools", "Architecture"], description: "Entity-to-DTO profiles with custom value resolvers" },
  { name: "Redis", types: ["Tools", "Database"], description: "Shopping baskets, response caching and SHA-256 cache keys" },
];

export const CATEGORIES = [
  { name: "Graduation Project", description: "Final-year university work", slug: "graduation-project" },
  { name: "Backend API", description: "API-first, service-oriented backends", slug: "backend-api" },
  { name: "Web Application", description: "End-to-end web applications with a user-facing interface", slug: "web-application" },
  { name: "Full-Stack", description: "Work spanning both the application server and the client", slug: "full-stack" },
  { name: "Enterprise Application", description: "Systems covering a whole business workflow and its administration", slug: "enterprise-application" },
  { name: "Game Development", description: "Published games built with a game engine", slug: "game-development" },
];

export const TAGS = [
  { name: "ASP.NET Core", slug: "aspnet-core" },
  { name: "Clean Architecture", slug: "clean-architecture" },
  { name: "Onion Architecture", slug: "onion-architecture" },
  { name: "Repository Pattern", slug: "repository-pattern" },
  { name: "Unit of Work", slug: "unit-of-work" },
  { name: "Specification Pattern", slug: "specification-pattern" },
  { name: "SOLID Principles", slug: "solid-principles" },
  { name: "Entity Framework Core", slug: "entity-framework-core" },
  { name: "SQL Server", slug: "sql-server" },
  { name: "Redis Caching", slug: "redis-caching" },
  { name: "Stripe Payments", slug: "stripe-payments" },
  { name: "SignalR Real-Time", slug: "signalr-real-time" },
  { name: "JWT Authentication", slug: "jwt-authentication" },
  { name: "Role-Based Access Control", slug: "role-based-access-control" },
  { name: "Race Condition Handling", slug: "race-condition-handling" },
  { name: "Background Services", slug: "background-services" },
  { name: "Multi-Format Reporting", slug: "multi-format-reporting" },
  { name: "Dual Database", slug: "dual-database" },
  { name: "Pagination", slug: "pagination" },
  { name: "AutoMapper", slug: "automapper" },
  { name: "Swagger", slug: "swagger" },
  { name: "REST API", slug: "rest-api" },
  { name: "ERD Design", slug: "erd-design" },
  { name: "React", slug: "react" },
  { name: "Django", slug: "django" },
  { name: "Python", slug: "python" },
  { name: "Unity", slug: "unity" },
  { name: "2D Platformer", slug: "2d-platformer" },
  { name: "OTP Verification", slug: "otp-verification" },
  { name: "Password Reset", slug: "password-reset" },
];

export const TECHNOLOGIES = [
  // Backend platform
  { name: ".NET 8", category: "Backend", description: "Target framework for every backend project in this portfolio" },
  { name: "ASP.NET Core 8", category: "Backend", description: "Web API framework used for all backend services" },
  { name: "RESTful API", category: "Backend", description: "HTTP interface style used across the projects" },
  { name: "ASP.NET Core Identity", category: "Backend", description: "User management, password hashing and roles in a separate database" },
  { name: "JWT Bearer Authentication", category: "Backend", description: "Stateless tokens carrying email, username, id and role claims" },
  { name: "SignalR", category: "Backend", description: "WebSocket hub pushing new orders and reservations to administrators" },
  { name: "BackgroundService", category: "Backend", description: "Hosted worker that keeps the reservation calendar in sync hourly" },
  { name: "Django", category: "Backend", description: "Python web framework used for the Knowly platform and the Neurea mobile backend" },
  { name: "Python", category: "Backend", description: "Programming language behind Django and the data-seeding scripts" },
  { name: "Unity", category: "Game Development", description: "Engine used to build and publish Sunny Land" },

  // Data
  { name: "Entity Framework Core", category: "Database", description: "ORM with Code-First migrations, Database-First reverse engineering and the Fluent API" },
  { name: "SQL Server", category: "Database", description: "Relational store, including filtered unique indexes enforcing booking rules" },
  { name: "Redis", category: "Database", description: "Shopping baskets, response caching and SHA-256 cache keys with per-user isolation" },

  // Client
  { name: "React", category: "Frontend", description: "18 components, protected routes and code-split pages for The Palate" },
  { name: "Tailwind CSS", category: "Frontend", description: "Responsive, mobile-first styling for the delivered frontends" },
  { name: "Stripe Elements", category: "Frontend", description: "Hosted card fields so payment data never reaches the server" },

  // Tooling
  { name: "AutoMapper", category: "Tools", description: "Six mapping profiles and 70+ mappings with custom value resolvers" },
  { name: "Swagger / OpenAPI", category: "Tools", description: "Generated API documentation with custom validation responses" },
  { name: "Postman", category: "Tools", description: "Endpoint testing and collection organisation" },
  { name: "Git & GitHub", category: "Tools", description: "Version control for every project in this portfolio" },
  { name: "ClosedXML", category: "Tools", description: "Excel report generation" },
  { name: "QuestPDF", category: "Tools", description: "PDF report generation" },
];

export const PROFILE = {
  fullName: "Mohamed Walid Abdullah",
  professionalTitle: "Backend .NET Developer",
  bio: "Computer Science graduate (CGPA 3.68 / 4.00) focused on backend development with ASP.NET Core. I design relational databases, build RESTful APIs, and apply modern architecture principles — Clean Architecture, Repository / Unit of Work and the Specification pattern — to keep software maintainable. Completed a 120-hour backend .NET diploma at Route Academy and shipped a graduation project graded A*, plus seven published projects spanning restaurant ordering, e-commerce, e-learning, enterprise administration and game development.",
  location: "Giza, Egypt",
  phone: "+201005041584",
  email: "Mewalid24636@gmail.com",
  // A3
  yearsOfExperience: 2,
  image: "ProfilePic.jpeg",
  aboutImage: "Suit.jpeg",
};

export const SOCIAL_LINKS = [
  {
    platform: "GitHub",
    username: "mohamedwalid24636",
    url: "https://github.com/mohamedwalid24636",
    icon: "GitHubBigIcon2.png",
  },
  {
    platform: "LinkedIn",
    username: "mohamed-walid",
    url: "https://www.linkedin.com/in/mohamed-walid-6b12a8314",
    icon: "LinkedInIcon.png",
  },
  {
    platform: "Email",
    username: "Mewalid24636@gmail.com",
    url: "mailto:Mewalid24636@gmail.com",
    icon: "GmailIcon.png",
  },
];

export const EXPERIENCES = [
  {
    jobTitle: "Backend .NET Developer Trainee",
    companyName: "Route Academy",
    location: "Giza, Egypt",
    employmentType: "Full Time",
    // A2
    startDate: "2024-01-01",
    endDate: "2025-12-31",
    isCurrent: false,
    logo: "RouteAcademyPicture.png",
    description: [
      "Completed a 120-hour Backend .NET diploma with hands-on training in database design, C#, advanced C#, OOP, SOLID principles, LINQ, Entity Framework Core, caching and Clean Architecture.",
      "Built ASP.NET Core MVC and Web API applications using Entity Framework Core (Code-First, Database-First, Fluent API, data annotations and migrations) together with ASP.NET Identity.",
      "Designed relational databases in SQL Server, producing ERDs, database schemas, stored procedures, views and indexing strategies.",
      "Applied Clean Architecture in practice through Onion Architecture, the Repository pattern, Unit of Work, dependency injection, JWT authentication, AutoMapper, SignalR, Swagger, Redis caching and Git / GitHub.",
    ].join("\n"),
  },
];

export const EDUCATIONS = [
  {
    institutionName: "Misr University for Science & Technology",
    degree: "Bachelor of Science",
    fieldOfStudy: "Computer Science",
    // A1
    startDate: "2022-09-01",
    endDate: "2026-07-01",
    isCurrent: false,
    logo: "MustUniversity.png",
    description: [
      "Graduated with an Excellent standing of CGPA 3.68 / 4.00.",
      "Graduation project (Neurea Mental Health Support System) graded A*.",
      "Information Technology course project — Laboratory Management System — ranked 2nd among the top projects and selected as a candidate for the university's future laboratory management system.",
    ].join("\n"),
  },
];

export const CERTIFICATIONS = [
  {
    name: "Backend .NET Diploma (120 hours)",
    issuingOrganization: "Route Academy",
    // A2
    issueDate: "2025-12-31",
    doesNotExpire: true,
    description:
      "Intensive backend programme covering C#, OOP, SOLID principles, LINQ, Entity Framework Core, SQL Server database design, caching and Clean Architecture, applied through hands-on ASP.NET Core MVC and Web API projects.",
  },
];

export const ACHIEVEMENTS = [
  {
    title: "Graduation project graded A*",
    description:
      "Awarded an A* for Neurea, a mental health support system whose ASP.NET Core backend and therapist/admin dashboard were integrated with an existing Django backend through a shared database and JWT-secured server-to-server communication.",
    // A1 — the CV gives the grade but no date; aligned with the graduation end date above.
    date: "2026-07-01",
    url: "https://github.com/mohamedwalid24636/Neurea.MentalHealthSupportSystemMergeDataBase-Asp.net-Django-",
    image: "GraduationPic.jpeg",
  },
  {
    title: "Graduated with Excellent standing — CGPA 3.68 / 4.00",
    description:
      "Completed the Computer Science programme at Misr University for Science & Technology with an Excellent cumulative grade point average.",
    // A1
    date: "2026-07-01",
  },
  {
    title: "Laboratory Management System ranked 2nd in the Information Technology course",
    description:
      "The layered ASP.NET Core Web API for laboratory assets, appointment scheduling, request handling, reporting and administrative workflows was ranked second among the top course projects and selected as a candidate for the university's future laboratory management system.",
    // No source states when the course project ran, so no date is claimed.
    date: null,
    url: "https://github.com/mohamedwalid24636/LaboratoriesManagementSystem",
  },
  {
    title: "Published Sunny Land, my first video game",
    description:
      "Designed, built and published a 2D platformer in Unity and C# — movement and jumping, enemy behaviours, health and damage, collectibles and scoring, audio, scene management and win / game-over states — and shared it publicly on Game Jolt.",
    date: null,
    // A7 — the post publishes the Game Jolt download through a LinkedIn redirect.
    url: "https://lnkd.in/d5c5fh93",
  },
];

export const SERVICES = [
  {
    title: "RESTful API Development",
    description:
      "Build and maintain ASP.NET Core Web APIs with clear resource-oriented contracts, consistent pagination and response envelopes, Swagger documentation and structured validation errors.",
    displayOrder: 1,
  },
  {
    title: "Relational Database Design",
    description:
      "Model normalised SQL Server schemas, produce ERDs and database designs, and work fluently with both Code-First and Database-First Entity Framework Core workflows.",
    displayOrder: 2,
  },
  {
    title: "Clean Architecture & Code Structure",
    description:
      "Separate concerns with Clean / Onion Architecture, applying Repository, Unit of Work, Specification and SOLID principles so the codebase is testable and easy to extend.",
    displayOrder: 3,
  },
  {
    title: "Caching & Performance",
    description:
      "Cut response times with Redis, a custom action-filter cache with per-user isolation and prefix-based invalidation, plus pagination on every collection endpoint.",
    displayOrder: 4,
  },
  {
    title: "Real-Time Features & Reporting",
    description:
      "Add live dashboards with SignalR, schedule work with background services, and export operational data to Excel, PDF and CSV from a single reporting abstraction.",
    displayOrder: 5,
  },
  {
    title: "Third-Party Integrations",
    description:
      "Integrate external services such as Stripe payments with server-side verification, idempotent order creation and hosted card fields, so credentials and card data stay off the server.",
    displayOrder: 6,
  },
];

export const RESUMES = [
  {
    title: "Mohamed Walid Abdullah — Curriculum Vitae",
    isActive: true,
    file: "Mohamed_Walid_Abdullah_CV.pdf",
  },
];

/* ------------------------------------------------------------------ projects */

export const PROJECTS = [
  {
    key: "palate",
    title: "The Palate Collective — Restaurant Management & Online Ordering Platform",
    shortDescription:
      "Multi-branch restaurant platform: online ordering with Stripe, race-condition-safe table reservations, a SignalR admin dashboard and Excel/PDF/CSV reporting on a 7-project Clean Architecture backend.",
    description: [
      "The Palate Collective is a Restaurant Management & Online Ordering Platform covering the complete restaurant workflow, from the customer experience through to administrative operations. Customers order food, pay online, reserve tables across multiple branches and track their activity, while administrators manage the entire business from a centralised dashboard.",
      "",
      "Role: backend developer. The React frontend was delivered by a team member.",
      "",
      "What it delivers",
      "- Online ordering with Stripe payments and server-side price verification, so a tampered basket can never change the amount charged.",
      "- Multi-branch table reservations driven by a live 7-day availability calendar, engineered with database-level race-condition protection so two customers can never successfully book the same slot twice.",
      "- Real-time admin notifications over SignalR whenever a new order or reservation arrives.",
      "- An admin dashboard for orders, reservations, menus, branches, working hours, customer feedback and contact messages, with business analytics and exports to Excel, PDF and CSV.",
      "- A modern, user-friendly interface with responsive layouts, protected role-based routes, code-split pages, Stripe Elements and a carefully chosen colour palette across desktop and mobile.",
      "",
      "Backend by the numbers",
      "- ASP.NET Core 8 Clean Architecture across 7 projects, 60+ endpoints, 150+ source files and 20 database entities.",
      "- Repository, Unit of Work, Pagination and 18 Specification classes, Redis caching with per-user isolation, JWT role-based security and a dual-database design separating application data from identity data.",
      "- Frontend: 18 reusable components, role-based routing, code-split pages, Stripe Elements and a SignalR client integration.",
      "",
      "Engineering decisions worth calling out",
      "- Reservation booking is guarded by a database-level filtered unique index as the first line of defence, a DbUpdateException fallback for the race that slips through, and a database transaction for atomicity.",
      "- Services are injected into the Service Manager facade as Func<IService> factories, so each one is resolved lazily and circular dependencies are avoided.",
      "- A BackgroundService runs hourly to extend the 7-day booking window, drop expired days and trim unused ones, so the calendar is always valid without manual work.",
      "- Caching is dual: per-user for order lists and global for the menu, with SHA-256 keys and prefix-based invalidation.",
      "- Image URLs are stored relative and resolved to absolute URLs by AutoMapper value resolvers, so ports and environments never need hardcoding.",
    ].join("\n"),
    status: "Completed",
    featured: true,
    // A4
    startDate: null,
    endDate: null,
    githubUrl: null,
    // The post publishes the deployed site through a LinkedIn redirect (A7).
    liveDemoUrl: "https://lnkd.in/eKXkB-ey",
    categories: ["Enterprise Application", "Backend API"],
    tags: [
      "Clean Architecture",
      "Repository Pattern",
      "Unit of Work",
      "Specification Pattern",
      "Redis Caching",
      "Stripe Payments",
      "SignalR Real-Time",
      "Race Condition Handling",
      "Background Services",
      "Multi-Format Reporting",
      "Dual Database",
      "Pagination",
      "React",
    ],
    technologies: [
      ".NET 8",
      "ASP.NET Core 8",
      "Entity Framework Core",
      "SQL Server",
      "Redis",
      "Stripe Elements",
      "SignalR",
      "AutoMapper",
      "React",
      "Tailwind CSS",
      "JWT Bearer Authentication",
      "ASP.NET Core Identity",
      "RESTful API",
      "Swagger / OpenAPI",
      "ClosedXML",
      "QuestPDF",
      "BackgroundService",
    ],
    // Screenshot taken from the LinkedIn Restaurand Post folder.
    cover: "LinkedIn Restaurand Post/HomePage.png",
    gallery: [
      { file: "LinkedIn Restaurand Post/Login.png", caption: "Customer login" },
      { file: "LinkedIn Restaurand Post/Registeration.png", caption: "Customer registration" },
      { file: "LinkedIn Restaurand Post/MenuItems.png", caption: "Menu items" },
      { file: "LinkedIn Restaurand Post/MenuItems_2.png", caption: "Menu items — alternate layout" },
      { file: "LinkedIn Restaurand Post/Categories.png", caption: "Menu categories" },
      { file: "LinkedIn Restaurand Post/SpecialOffers.png", caption: "Special offers" },
      { file: "LinkedIn Restaurand Post/Basket.png", caption: "Shopping basket" },
      { file: "LinkedIn Restaurand Post/Payment.png", caption: "Stripe payment step" },
      { file: "LinkedIn Restaurand Post/MyOrders.png", caption: "Customer order history" },
      { file: "LinkedIn Restaurand Post/ReservationForm.png", caption: "Table reservation form" },
      { file: "LinkedIn Restaurand Post/AvailabilitySlots.png", caption: "Live 7-day availability calendar" },
      { file: "LinkedIn Restaurand Post/MyReservations.png", caption: "My reservations" },
      { file: "LinkedIn Restaurand Post/Branches&Location.png", caption: "Branches and locations" },
      { file: "LinkedIn Restaurand Post/CustomerFeedBack.png", caption: "Customer feedback form" },
      { file: "LinkedIn Restaurand Post/Feedbacks.png", caption: "Admin feedback inbox" },
      { file: "LinkedIn Restaurand Post/Reports.png", caption: "Report generation and export" },
      { file: "LinkedIn Restaurand Post/AdminDashboard.png", caption: "Admin dashboard" },
      { file: "LinkedIn Restaurand Post/AdminDashboard2.png", caption: "Admin dashboard — revenue and order analytics" },
      { file: "LinkedIn Restaurand Post/AdminBranches&Hours.png", caption: "Admin: branches and working hours" },
      { file: "LinkedIn Restaurand Post/AdminMenuItems.png", caption: "Admin: menu management" },
      { file: "LinkedIn Restaurand Post/AdminOrders.png", caption: "Admin: order management" },
      { file: "LinkedIn Restaurand Post/AdminContactMessages.png", caption: "Admin: contact messages" },
    ],
  },

  {
    key: "ecommerce",
    title: "E-Commerce Backend API — Talabat Ordering Platform",
    shortDescription:
      "Production-style ASP.NET Core 8 backend for a Talabat-style ordering platform: catalogue, Redis baskets, Stripe PaymentIntents, JWT auth and a 10-step order workflow with server-side price verification.",
    description: [
      "A full-stack food-ordering platform inspired by the real-world Talabat delivery app. The backend is built with ASP.NET Core 8 following Clean Architecture, providing a complete REST API for product catalogue management, user authentication, shopping basket operations, Stripe payment processing, order management and delivery tracking. The solution is organised into 7 .NET projects with strict dependency direction — the web layer is the only project that references all others.",
      "",
      "Role: backend developer. Frontend delivered by a team member.",
      "",
      "What it delivers",
      "- Paginated product catalogue with search, brand, type and sort filters, composed through the Specification pattern rather than raw SQL.",
      "- Shopping baskets held in Redis with a 30-day TTL, plus a custom action-filter cache that cut response time by roughly 75% (about 60 ms down to 15 ms).",
      "- Stripe PaymentIntent lifecycle handling all three states: create a new intent, update a pending intent, or create a fresh intent when the previous one already completed — which prevents a double charge.",
      "- A 10-step order creation workflow that re-reads every price from SQL Server, verifies the payment succeeded through Stripe, and is idempotent against duplicate PaymentIntent ids.",
      "- JWT authentication with role claims, ASP.NET Core Identity in its own database, seeded Admin and SuperAdmin roles, and structured error responses produced by a global exception middleware.",
      "",
      "Stack",
      "- C# / .NET 8, ASP.NET Core 8, Entity Framework Core 8.0.25, SQL Server, Redis (StackExchange.Redis), ASP.NET Core Identity 8.0.23, JWT bearer auth, AutoMapper 12, Stripe.net 50.3.0 and Swashbuckle 6.6.2.",
      "- 23 API endpoints across products, baskets, orders, payments, authentication and machine reports.",
      "",
      "Design decisions worth calling out",
      "- A dictionary-cached Unit of Work shares one DbContext across every repository in a business transaction, so commits are atomic and repositories are created lazily.",
      "- The Specification evaluator aggregates criteria, includes, ordering and pagination onto the IQueryable in sequence, so new queries are added as new classes — no repository changes.",
      "- Prices arriving from the client are never trusted: both OrderService and PaymentService overwrite basket prices with database prices before totalling.",
      "- A CacheAttribute action filter builds keys that include the user's email for personalised data, with a configurable TTL.",
    ].join("\n"),
    status: "Completed",
    featured: true,
    startDate: null,
    endDate: null,
    githubUrl: "https://github.com/mohamedwalid24636/E-Commerse.Website.git",
    liveDemoUrl: null,
    categories: ["Backend API"],
    tags: [
      "Clean Architecture",
      "Onion Architecture",
      "Repository Pattern",
      "Unit of Work",
      "Specification Pattern",
      "SOLID Principles",
      "Redis Caching",
      "Stripe Payments",
      "JWT Authentication",
      "Dual Database",
      "Pagination",
      "AutoMapper",
      "Swagger",
      "REST API",
    ],
    technologies: [
      ".NET 8",
      "ASP.NET Core 8",
      "Entity Framework Core",
      "SQL Server",
      "Redis",
      "Stripe Elements",
      "AutoMapper",
      "JWT Bearer Authentication",
      "ASP.NET Core Identity",
      "RESTful API",
      "Swagger / OpenAPI",
    ],
    cover: "Talabate LinkedIn Post/HomePage.png",
    gallery: [
      { file: "Talabate LinkedIn Post/Shope.png", caption: "Product catalogue" },
      { file: "Talabate LinkedIn Post/Product.png", caption: "Product details" },
      { file: "Talabate LinkedIn Post/Baskit.png", caption: "Shopping basket" },
      { file: "Talabate LinkedIn Post/CheckOut.png", caption: "Checkout" },
      { file: "Talabate LinkedIn Post/PaymentProcess.png", caption: "Stripe payment processing" },
      { file: "Talabate LinkedIn Post/Visa.png", caption: "Visa card payment option" },
      { file: "Talabate LinkedIn Post/Successful.png", caption: "Order placed successfully" },
      { file: "Talabate LinkedIn Post/MyOrders.png", caption: "My orders" },
      { file: "Talabate LinkedIn Post/DeliverMethod.png", caption: "Delivery method selection" },
      { file: "Talabate LinkedIn Post/Review.png", caption: "Order review" },
      { file: "Talabate LinkedIn Post/AuthenticationController.png", caption: "Authentication controller" },
      { file: "Talabate LinkedIn Post/AllControllers.png", caption: "API controllers" },
      {
        file: "Talabate LinkedIn Post/Basket,Orders,PaymentControllers.png",
        caption: "Basket, orders and payment controllers",
      },
      {
        file: "Talabate LinkedIn Post/Screenshot 2026-08-20 175718.png",
        caption: "Portal capture at 17:57:18 on 20 Aug 2026",
      },
      {
        file: "Talabate LinkedIn Post/Screenshot 2026-08-20 175737.png",
        caption: "Portal capture at 17:57:37 on 20 Aug 2026",
      },
      {
        file: "Talabate LinkedIn Post/Talabat.mp4",
        caption: "Ordering flow walkthrough",
      },
    ],
  },

  {
    key: "neurea",
    title: "Neurea — Mental Health Support System",
    shortDescription:
      "Graduation project (graded A*): an ASP.NET Core backend and therapist/admin dashboard integrated with an existing Django backend through a shared database and JWT-secured server-to-server calls.",
    description: [
      "A multi-platform mental health support system that lets patients access mental health services while therapists and administrators manage appointments, consultations and platform operations.",
      "",
      "What I built",
      "- The ASP.NET Core backend together with the therapist and admin dashboard, covering appointments, consultations and platform operations.",
      "- The integration layer that joins this backend to an existing Django backend through a shared database and JWT-secured server-to-server communication, so the web platform and the mobile app stay in sync.",
      "- A data-access and API layer built with Entity Framework Core using Database-First with reverse engineering, SQL Server, the Repository and Unit of Work patterns, AutoMapper and RESTful API design.",
      "",
      "Outcome",
      "- Graded A* as the Computer Science graduation project at Misr University for Science & Technology.",
    ].join("\n"),
    status: "Completed",
    featured: true,
    startDate: null,
    endDate: null,
    githubUrl:
      "https://github.com/mohamedwalid24636/Neurea.MentalHealthSupportSystemMergeDataBase-Asp.net-Django-.git",
    liveDemoUrl: null,
    categories: ["Graduation Project", "Full-Stack"],
    tags: [
      "ASP.NET Core",
      "Entity Framework Core",
      "SQL Server",
      "Repository Pattern",
      "Unit of Work",
      "JWT Authentication",
      "AutoMapper",
      "Django",
      "REST API",
    ],
    technologies: [
      ".NET 8",
      "ASP.NET Core 8",
      "Entity Framework Core",
      "SQL Server",
      "AutoMapper",
      "Django",
      "Python",
      "JWT Bearer Authentication",
      "RESTful API",
    ],
    // No screenshot exists in NeededData, so the repository's existing project card is used.
    cover: "@asset:public/assets/images/projects/neurea.svg",
    gallery: [],
  },

  {
    key: "laboratory",
    title: "Laboratory Management System",
    shortDescription:
      "Layered ASP.NET Core Web API for laboratory assets, appointment scheduling, request handling, reporting and admin workflows — with authentication and OTP email verification built from scratch, without ASP.NET Identity.",
    description: [
      "An Information Technology course project that ranked 2nd among the top course projects and was selected as a candidate for the university's future laboratory management system.",
      "",
      "What it delivers",
      "- A layered ASP.NET Core Web API for laboratory asset management, appointment scheduling, request handling, reporting and administrative workflows.",
      "- A custom authentication and authorization system built from scratch without ASP.NET Identity: JWT access and refresh tokens, OTP e-mail verification, role-based access control, instructor onboarding and image upload.",
      "- Reusable data access and business layers using the Generic Repository, Generic Service and Unit of Work patterns, extending the generic implementations with entity-specific business logic while keeping duplication to a minimum.",
    ].join("\n"),
    status: "Completed",
    featured: false,
    startDate: null,
    endDate: null,
    githubUrl: "https://github.com/mohamedwalid24636/LaboratoriesManagementSystem",
    liveDemoUrl: null,
    categories: ["Web Application", "Backend API"],
    tags: [
      "Clean Architecture",
      "Repository Pattern",
      "Unit of Work",
      "SOLID Principles",
      "Entity Framework Core",
      "SQL Server",
      "JWT Authentication",
      "Role-Based Access Control",
      "OTP Verification",
      "ERD Design",
      "REST API",
    ],
    technologies: [
      ".NET 8",
      "ASP.NET Core 8",
      "Entity Framework Core",
      "SQL Server",
      "AutoMapper",
      "JWT Bearer Authentication",
      "RESTful API",
    ],
    cover: "@asset:public/assets/images/projects/laboratory.svg",
    gallery: [],
  },

  {
    key: "company-management",
    title: "Company Management System",
    shortDescription:
      "Administration portal covering users, roles, employees and departments with full CRUD, role-based access, self-service password change and e-mailed password-reset links.",
    description: [
      "A web administration system for running a company's internal records: who the users are, what each role may do, which employees belong to which department, and how access is recovered when someone forgets their password.",
      "",
      "What it delivers",
      "- Users: listing, search, details, create, edit and delete, with a self-service change-password screen.",
      "- Roles: listing, details, create, edit and delete, with permissions driving what each admin can reach.",
      "- Employees: listing with detailed per-employee views.",
      "- Departments: listing, details, create, edit and delete, with the department each employee belongs to.",
      "- Registration and login, plus a guest landing view for visitors who are not signed in.",
      "- Password recovery by e-mail: an admin can send a reset link, the recipient sees a confirmation that the link was sent, and opening the link lands on the reset screen.",
      "",
      "A note on the source material",
      "- The LinkedIn post text that accompanied this project is a 0-byte file in NeededData, so the description above is derived from the 25 project screenshots. No source file states the stack, dates or repository, so only the screens are claimed here.",
    ].join("\n"),
    status: "Completed",
    featured: false,
    startDate: null,
    endDate: null,
    githubUrl: null,
    liveDemoUrl: null,
    categories: ["Web Application", "Enterprise Application"],
    tags: [
      "Role-Based Access Control",
      "Password Reset",
      "JWT Authentication",
      "REST API",
    ],
    // A6
    technologies: [".NET 8", "ASP.NET Core 8", "SQL Server"],
    cover: "CompanyManagmentSystemLinkedInPostData/HomePage.png",
    gallery: [
      { file: "CompanyManagmentSystemLinkedInPostData/Login.png", caption: "Login" },
      { file: "CompanyManagmentSystemLinkedInPostData/Register.png", caption: "Registration" },
      {
        file: "CompanyManagmentSystemLinkedInPostData/WelcomeWithOutLogin.png",
        caption: "Guest landing view before sign-in",
      },
      { file: "CompanyManagmentSystemLinkedInPostData/AllUsers.png", caption: "Users list" },
      { file: "CompanyManagmentSystemLinkedInPostData/UserDetails.png", caption: "User details" },
      { file: "CompanyManagmentSystemLinkedInPostData/EditUser.png", caption: "Edit user" },
      { file: "CompanyManagmentSystemLinkedInPostData/DeleteUser.png", caption: "Delete user" },
      { file: "CompanyManagmentSystemLinkedInPostData/AllRoles.png", caption: "Roles list" },
      { file: "CompanyManagmentSystemLinkedInPostData/RoleDetails.png", caption: "Role details" },
      {
        file: "CompanyManagmentSystemLinkedInPostData/RoleDetails Test.png",
        caption: "Role details — empty state",
      },
      { file: "CompanyManagmentSystemLinkedInPostData/EditRole.png", caption: "Edit role" },
      { file: "CompanyManagmentSystemLinkedInPostData/DeleteRole.png", caption: "Delete role" },
      { file: "CompanyManagmentSystemLinkedInPostData/AllEmployees.png", caption: "Employees list" },
      { file: "CompanyManagmentSystemLinkedInPostData/EmployeeDetails.png", caption: "Employee details" },
      {
        file: "CompanyManagmentSystemLinkedInPostData/EmployeeDetails2.png",
        caption: "Employee details — extended view",
      },
      {
        file: "CompanyManagmentSystemLinkedInPostData/EmployeeDetailstest.png",
        caption: "Employee details — populated data test",
      },
      { file: "CompanyManagmentSystemLinkedInPostData/Departments.png", caption: "Departments list" },
      { file: "CompanyManagmentSystemLinkedInPostData/DepartmentDetails.png", caption: "Department details" },
      {
        file: "CompanyManagmentSystemLinkedInPostData/DepartmentDetails2.png",
        caption: "Department details — extended view",
      },
      { file: "CompanyManagmentSystemLinkedInPostData/EditDepartment.png", caption: "Edit department" },
      { file: "CompanyManagmentSystemLinkedInPostData/DeleteDepartment.png", caption: "Delete department" },
      { file: "CompanyManagmentSystemLinkedInPostData/ChangePassword.png", caption: "Change password" },
      {
        file: "CompanyManagmentSystemLinkedInPostData/SendResetPasswordLink.png",
        caption: "Send password reset link",
      },
      {
        file: "CompanyManagmentSystemLinkedInPostData/LinkSendSuccesfully.png",
        caption: "Reset link sent — confirmation",
      },
      { file: "CompanyManagmentSystemLinkedInPostData/Link.png", caption: "Password reset landing page" },
      {
        file: "CompanyManagmentSystemLinkedInPostData/CompantManagementSystem.mp4",
        caption: "Full system walkthrough",
      },
    ],
  },

  {
    key: "knowly",
    title: "Knowly — E-Learning Platform",
    shortDescription:
      "My first backend project: a Django E-Learning platform where instructors publish courses and students browse, filter and open course content, with profiles and a support page.",
    description: [
      "Knowly is an E-Learning platform built with Django. The idea was simple: a place where instructors can publish courses and students can browse, explore and access educational content in an organised way.",
      "",
      "Role: backend developer.",
      "",
      "What it delivers",
      "- Courses page listing the published catalogue.",
      "- Category filtering so students can narrow the catalogue.",
      "- Course details pages.",
      "- Authentication and user management.",
      "- User profiles.",
      "- Contact and support page.",
      "- An instructor-facing add-course form and the Django admin panel behind it.",
      "",
      "What it taught me",
      "- Django was completely new to me, and this was my first real backend experience. I learned how models, views, forms, templates, URLs, static files and every other application component come together to serve real users.",
      "- I started without an ERD, a database schema or a clear development plan, creating tables and relationships as I went. That unstructured approach produced inconsistent database design and poor integration between parts of the system.",
      "- The consequences were concrete: code duplication that grew with the project, and rising effort for even small changes — sometimes a single change meant touching almost the whole codebase.",
      "- The lesson stuck: building software starts with designing the system, not writing the code.",
    ].join("\n"),
    status: "Completed",
    featured: false,
    startDate: null,
    endDate: null,
    // A5
    githubUrl: null,
    liveDemoUrl: null,
    categories: ["Web Application"],
    tags: ["Django", "Python", "REST API"],
    technologies: ["Django", "Python"],
    cover: "LomyLinkedInPost/ScreenShots/HomePage.png",
    gallery: [
      { file: "LomyLinkedInPost/ScreenShots/LoginPage.png", caption: "Login page" },
      { file: "LomyLinkedInPost/ScreenShots/RegisterPage.png", caption: "Registration page" },
      { file: "LomyLinkedInPost/ScreenShots/ProfilePage.png", caption: "User profile page" },
      { file: "LomyLinkedInPost/ScreenShots/AddCourseForm.png", caption: "Instructor add-course form" },
      { file: "LomyLinkedInPost/ScreenShots/ContactUsPage.png", caption: "Contact and support page" },
      { file: "LomyLinkedInPost/ScreenShots/DjangoAdminPanel.png", caption: "Django admin panel" },
      {
        file: "LomyLinkedInPost/KnowlyWebsiteRecordVideo.mp4",
        caption: "Platform walkthrough",
      },
    ],
  },

  {
    key: "sunny-land",
    title: "Sunny Land — 2D Platformer",
    shortDescription:
      "My first published video game, built in Unity with C#: collect gems, defeat opossums and eagles, manage health, and reach the final house to win.",
    description: [
      "Sunny Land is a 2D platformer built and published with Unity and C#. The player collects gems and cherries to raise their score, faces enemies such as opossums and eagles, loses health when hit, and defeats an enemy by jumping on it. The player loses when their health reaches zero or when they fall off the map, and wins by reaching the final house.",
      "",
      "Features",
      "- Player movement, jumping and falling mechanics.",
      "- Enemies: opossums and eagles.",
      "- Health and damage system.",
      "- Collectible items and scoring system.",
      "- Audio effects.",
      "- Main menu and scene management.",
      "- Win and game-over states.",
      "",
      "What it taught me",
      "- Unity's component-based architecture in practice: GameObjects, Components, Prefabs, Scenes and the editor workflow.",
      "- Building complete levels with tilemaps, organising gameplay objects, managing scenes and connecting gameplay systems to UI and audio.",
      "- Gameplay programming in C#: movement, jumping, enemy behaviour, collectibles, scoring, health and game-state logic.",
      "- Physics, collisions and animation with Rigidbody2D, colliders, triggers, Animator Controllers, animation states, parameters and transitions.",
      "- The bigger point: software engineering is not limited to one track. Strong fundamentals carry across backend, web and games — technologies change, engineering principles do not.",
    ].join("\n"),
    status: "Published",
    featured: false,
    startDate: null,
    endDate: null,
    // A7 — the post publishes the repository through a LinkedIn redirect.
    githubUrl: "https://lnkd.in/d5dUTYmB",
    liveDemoUrl: "https://lnkd.in/d5c5fh93",
    categories: ["Game Development"],
    tags: ["Unity", "2D Platformer"],
    technologies: ["Unity"],
    // NeededData holds no screenshot for this project, only the gameplay video below, so the
    // repository's project card is used as the cover.
    cover: "@asset:public/assets/images/projects/sunny-land.svg",
    gallery: [
      {
        file: "SunnyLandLinkedInPost/SunnyLandFinalVideo.mp4",
        caption: "Gameplay walkthrough",
      },
    ],
  },
];

/* --------------------------------------------------------------- blog posts */

/**
 * The LinkedIn posts and technical reports converted into professional articles. Each post is
 * written for a reader of the site, not copied verbatim from the post.
 */
export const BLOG_POSTS = [
  {
    key: "race-conditions",
    title: "Two Customers, One Table: Booking Without Double Bookings",
    shortDescription:
      "How a live reservation calendar stays honest under concurrency — a filtered unique index, a transaction, an exception fallback and an hourly background worker.",
    status: "Published",
    cover: "LinkedIn Restaurand Post/AvailabilitySlots.png",
    content: [
      "## The problem is not the calendar",
      "",
      "A reservation calendar looks like a read-only grid: seven days, opening hours, a slot per hour. The hard part is not drawing it — it is keeping it true when two people click the same slot within the same second.",
      "",
      "A check-then-insert is not enough:",
      "",
      "```csharp",
      "if (!await IsTakenAsync(slot))",
      "    await InsertAsync(slot);   // two callers can both pass this check",
      "```",
      "",
      "Both requests read \"free\", both insert, and the customer who gets there second only finds out when they turn up.",
      "",
      "## Layer 1 — a filtered unique index",
      "",
      "The rule belongs in the database, not in application code. A filtered unique index over the active statuses makes double booking impossible even when two requests arrive at the same instant:",
      "",
      "```sql",
      "CREATE UNIQUE INDEX UX_Reservations_Slot",
      "ON Reservations (BranchId, ReservationDate, TimeSlotId)",
      "WHERE Status IN (0, 1);   -- Pending or Approved",
      "```",
      "",
      "Filtering matters: a cancelled reservation must free its slot again, and without the `WHERE` clause a single slot could only ever be used once, ever.",
      "",
      "## Layer 2 — a transaction for atomicity",
      "",
      "Booking is more than one statement: read the slot, verify the customer, write the reservation, write the audit row. Wrapping them in a database transaction means a failure halfway leaves no orphaned reservation behind.",
      "",
      "## Layer 3 — an exception fallback",
      "",
      "Even with the index, a caller can lose the race after the in-memory check passes. That surfaces as a `DbUpdateException` from the unique-constraint violation, and it is caught to return a friendly message rather than a 500:",
      "",
      "```csharp",
      "try",
      "{",
      "    await _unitOfWork.SaveChangesAsync();",
      "}",
      "catch (DbUpdateException ex) when (IsUniqueViolation(ex))",
      "{",
      "    return Result.Failure(\"That slot has just been taken. Please pick another one.\");",
      "}",
      "```",
      "",
      "Three layers, each cheap, together making the failure mode a friendly message instead of a double booking.",
      "",
      "## Keeping the window valid without a cron job",
      "",
      "A rolling 7-day window needs future days to exist and past days to disappear. Doing that in a request handler is wasteful, so a hosted `BackgroundService` runs hourly:",
      "",
      "1. Remove expired days (and their reservations).",
      "2. Create future days to keep the window at 7 days.",
      "3. Extend the window when days fill up.",
      "4. Trim excess unreserved future days.",
      "",
      "The frontend then always reads a valid calendar with no manual intervention and no request-time writes.",
      "",
      "## What I would take further",
      "",
      "- A database-level lock hint (`UPDLOCK`) on the availability read when write contention climbs.",
      "- An idempotency key per booking attempt, so a retried request returns the original reservation instead of a new one.",
      "- A short-lived hold (2–3 minutes) on a slot while the customer completes checkout, which removes most of the double-book race at the source.",
    ].join("\n"),
  },
  {
    key: "never-trust-the-client",
    title: "Never Trust the Client: Server-Side Price Verification",
    shortDescription:
      "A tampered basket should not be able to change what a customer pays. Overriding client prices with database prices, and making order creation idempotent.",
    status: "Published",
    cover: "Talabate LinkedIn Post/Baskit.png",
    content: [
      "## The cheapest vulnerability in an e-commerce backend",
      "",
      "It takes one line of client code to attack:",
      "",
      "```javascript",
      "basket.items[0].price = 1;   // pay one unit price for anything",
      "```",
      "",
      "If the backend adds up the prices it was given, the attacker decides what they pay. That is not a theoretical bug — it is the default outcome of any API that trusts its input for money.",
      "",
      "## The fix is boring and total",
      "",
      "The basket holds only *what* the customer wants. The database holds *what it costs*. Totals are always computed from the database:",
      "",
      "```csharp",
      "foreach (var item in Basket.Items)",
      "{",
      "    var product = await ProductRepo.GetByIdAsync(item.Id)",
      "        ?? throw new ProductNotFoundException(item.Id);",
      "",
      "    item.Price = product.Price;   // override whatever the client sent",
      "}",
      "",
      "SubTotal = Basket.Items.Sum(i => i.Price * i.Quantity);",
      "```",
      "",
      "The client can change quantities — it cannot change prices. The same override runs in the payment service, so the amount sent to Stripe is already server-verified.",
      "",
      "## The same principle for the payment itself",
      "",
      "A client that says \"payment succeeded\" means nothing. Before an order is written, the server asks Stripe:",
      "",
      "```csharp",
      "var intent = await _paymentIntentService.GetAsync(paymentIntentId);",
      "",
      "if (intent.Status != \"succeeded\")",
      "    throw new PaymentNotCompletedException(paymentIntentId);",
      "```",
      "",
      "## Idempotency: a retry must not become a second order",
      "",
      "Networks retry. Users double-click. If the same `PaymentIntentId` is processed twice you get two orders for one payment. Order creation therefore checks for an existing order with that intent id and returns it instead of creating another:",
      "",
      "1. Map the address DTO to the order address.",
      "2. Load the basket from Redis.",
      "3. Verify the `PaymentIntentId` exists.",
      "4. Verify through Stripe that it succeeded.",
      "5. Reject or reuse if an order with that intent already exists.",
      "6. For each item, re-read the product and take the price from SQL Server.",
      "7. Load the delivery method from the database.",
      "8. Compute the subtotal from the verified prices.",
      "9. Save through the Unit of Work.",
      "10. Return the mapped order DTO.",
      "",
      "## Keep card data away from the server entirely",
      "",
      "The better fix for payment details is not verifying them, it is never receiving them. Stripe Elements renders hosted card fields, so raw card numbers go straight from the browser to Stripe and only the resulting token reaches the backend.",
      "",
      "## The takeaway",
      "",
      "Client input is a *request*, not a *fact*. Validate structure with the framework, then re-derive every value that affects money, permissions or availability from a source the client cannot touch.",
    ].join("\n"),
  },
  {
    key: "clean-architecture-in-practice",
    title: "Clean Architecture in Practice: 7 Projects, 60+ Endpoints",
    shortDescription:
      "What strict dependency inversion actually buys you — the layer map, the generic repository, the Specification pattern, factory delegates and a global exception middleware.",
    status: "Published",
    cover: "Talabate LinkedIn Post/AllControllers.png",
    content: [
      "## The layout",
      "",
      "Seven projects, and only the outermost one knows about all the others:",
      "",
      "```text",
      "E-Commerse.Web            <- composition root: DI, middleware, startup",
      "  Core/DomanLayer          <- entities, contracts, exceptions   (no external dependencies)",
      "  Core/ServiceAbstraction  <- service interfaces",
      "  Core/Service             <- business logic, specifications, mapping profiles",
      "  Infrastructure/Persistence   <- EF Core, Redis, repositories, seeding",
      "  Infrastructure/Presentation <- controllers, action filters",
      "  Shared                   <- DTOs, query params, error models, pagination",
      "```",
      "",
      "Controllers depend on interfaces, never on implementations. The Domain layer has zero external dependencies. Everything is resolved by the container from the composition root, so a service can be swapped for a fake without touching a controller.",
      "",
      "## One repository, every entity",
      "",
      "A generic repository over `BaseEntity<TKey>` gives every aggregate CRUD plus specification-based queries. The Unit of Work shares a single `DbContext` across all of them and caches instances per entity type:",
      "",
      "```csharp",
      "public IGenericRepository<TEntity, TKey> GetRepository<TEntity, TKey>()",
      "    where TEntity : BaseEntity<TKey>",
      "{",
      "    var name = typeof(TEntity).Name;",
      "    if (_repositories.TryGetValue(name, out var cached))",
      "        return (IGenericRepository<TEntity, TKey>)cached;",
      "",
      "    var repo = new GenericRepository<TEntity, TKey>(_dbContext);",
      "    _repositories[name] = repo;",
      "    return repo;",
      "}",
      "```",
      "",
      "One context per business transaction means commits are atomic; lazy caching means no per-entity DI overhead.",
      "",
      "## Queries as objects, not LINQ chains",
      "",
      "Filtering, sorting, including and paginating all live in specification classes that compose:",
      "",
      "```csharp",
      "public class ProductsSpecification(ProductQueryParams q)",
      "    : base(p => (!q.BrandId.HasValue || p.BrandId == q.BrandId)",
      "            && (!q.TypeId.HasValue || p.TypeId == q.TypeId)",
      "            && (string.IsNullOrWhiteSpace(q.Search)",
      "                || p.Name.ToLower().Contains(q.Search.ToLower())))",
      "{",
      "    AddInclude(p => p.ProductBrand);",
      "    AddInclude(p => p.ProductType);",
      "    ApplyPagination(q.PageSize, q.PageIndex);",
      "}",
      "```",
      "",
      "An evaluator turns the specification into an `IQueryable` chain. New business queries are new classes — the repository never changes. That is the Open/Closed Principle paying rent on every sprint.",
      "",
      "## Factory delegates instead of eager injection",
      "",
      "The Service Manager facade receives `Func<IService>` instead of services:",
      "",
      "```csharp",
      "public class ServiceManager(",
      "    Func<IProductService> product,",
      "    Func<IBasketService> basket,",
      "    Func<IAuthenticationService> auth) : IServiceManager",
      "{",
      "    public IProductService ProductService => product.Invoke();",
      "}",
      "```",
      "",
      "Services are built when first touched, which removes the circular dependencies that direct constructor injection would create between facades.",
      "",
      "## Exceptions that become status codes",
      "",
      "A domain exception hierarchy plus one middleware removes try/catch from controllers:",
      "",
      "```csharp",
      "response.StatusCode = ex switch",
      "{",
      "    NotFoundException              => StatusCodes.Status404NotFound,",
      "    UnauthorizedException          => StatusCodes.Status401Unauthorized,",
      "    CreateUserBadRequestException  => GetBadRequest(ex, response),",
      "    _                              => StatusCodes.Status500InternalServerError",
      "};",
      "```",
      "",
      "Fifteen exception classes in the restaurant project; the mapping is exhaustive and centralised, so a new business error never needs a controller change.",
      "",
      "## What it cost, and what it bought",
      "",
      "It costs more files and a little indirection up front. In exchange: a testable core, swappable infrastructure, a codebase that survives team growth, and a compiler-enforced boundary nobody can quietly walk through.",
    ].join("\n"),
  },
  {
    key: "design-before-code",
    title: "Design Before You Code: What My First Django Project Taught Me",
    shortDescription:
      "I shipped my first backend without an ERD or a plan. It worked — and it taught me exactly what the missing design cost.",
    status: "Published",
    cover: "LomyLinkedInPost/ScreenShots/HomePage.png",
    content: [
      "## Knowly",
      "",
      "Knowly was an E-Learning platform built with Django: instructors publish courses, students browse them, filter by category, open course details, manage their profile and reach a contact page. It was my first real backend, and at the time it felt like a huge achievement.",
      "",
      "Django was completely new to me, and it became the project where I learned how models, views, forms, templates, URLs and static files all come together to serve real users.",
      "",
      "## How I built it",
      "",
      "Badly. I started with no ERD, no database schema and no development plan. I created tables and relationships as I needed them, feature by feature.",
      "",
      "It worked. The platform ran, the screens rendered, the features were there.",
      "",
      "## What it cost",
      "",
      "- **Inconsistent database design.** Tables created for one feature did not line up with tables created for another.",
      "- **Poor integration between parts of the system.** Every seam had to be handled by hand.",
      "- **Code duplication that grew with the project.** The same logic, written again for the next feature.",
      "- **Rising cost of change.** Small changes took longer, and sometimes a single change meant modifying almost the entire codebase.",
      "",
      "> Building software starts with designing the system, not writing the code.",
      "",
      "## What I do differently now",
      "",
      "Every backend project since then starts the same way:",
      "",
      "1. **Draw the ERD.** Entities, relationships, cardinalities, and the owned value types that keep addresses from being orphaned.",
      "2. **Write the schema.** Tables, keys, cascade rules and the indexes that back the filters.",
      "3. **Name the patterns up front.** Repository, Unit of Work, Specification — decided before the first service exists.",
      "4. **Only then write code.**",
      "",
      "The Laboratory Management System is the clearest example of the difference. Its Generic Repository, Generic Service and Unit of Work layers meant the entity-specific logic was *added* to a reusable base, not reinvented per feature — the exact duplication that Knowly taught me to avoid.",
      "",
      "## The lesson that outlasted the framework",
      "",
      "I have moved from Django to ASP.NET Core since then, and from projects I designed badly to projects I designed first. The framework changed; the lesson did not.",
    ].join("\n"),
  },
  {
    key: "building-a-game",
    title: "Building My First Video Game with Unity",
    shortDescription:
      "Sunny Land — a 2D platformer published end to end. Gameplay systems, tilemap level design, physics, animation and audio, and what it taught me about engineering.",
    status: "Published",
    cover: "@asset:public/assets/images/projects/sunny-land.svg",
    content: [
      "## A different kind of project",
      "",
      "Every project so far had pushed me into a new area of software engineering. This time it was game development: building and publishing my first video game using Unity and C#.",
      "",
      "## Sunny Land",
      "",
      "A 2D platformer. The player collects gems and cherries to raise their score while facing enemies such as opossums and eagles. Taking damage reduces health, and jumping on an enemy defeats it. The player loses when health reaches zero or when they fall off the map — and wins by reaching the final house.",
      "",
      "## Features",
      "",
      "- Player movement, jumping and falling mechanics",
      "- Enemies (opossums and eagles)",
      "- Health and damage system",
      "- Collectible items and scoring system",
      "- Audio effects",
      "- Main menu and scene management",
      "- Win and game over states",
      "",
      "## What I learned",
      "",
      "### Unity engine and level development",
      "",
      "Hands-on experience with Unity's component-based architecture — GameObjects, Components, Prefabs, Scenes and the editor workflow — and building complete levels with tilemaps, organising gameplay objects, managing scenes and connecting gameplay systems to UI and audio.",
      "",
      "### Gameplay programming",
      "",
      "Player movement, jumping mechanics, enemy behaviours, collectibles, scoring, health management and game-state logic, all written in C# scripts.",
      "",
      "### Physics, collisions and animations",
      "",
      "Working with `Rigidbody2D`, colliders and triggers for responsive, interactive gameplay, and with Animator Controllers, animation states, parameters and transitions to drive it.",
      "",
      "## The takeaway",
      "",
      "This project introduced me to the complete game development workflow — from gameplay systems and level design through to animations, physics, UI and audio assembled into something playable.",
      "",
      "The final lesson was the most valuable one: software engineering is not limited to a single track. Strong fundamentals and engineering principles apply whether the work is backend, web or games. Technologies change; engineering principles remain the same.",
    ].join("\n"),
  },
  {
    key: "redis-caching",
    title: "Redis Caching in ASP.NET Core: From 60 ms to 15 ms",
    shortDescription:
      "A custom action-filter cache with SHA-256 keys, per-user isolation, prefix-based invalidation and a dual caching strategy — plus why Redis belongs in the basket.",
    status: "Published",
    cover: "Talabate LinkedIn Post/Product.png",
    content: [
      "## Where the time was going",
      "",
      "The catalogue endpoints were answering in roughly 60 ms. Most of that was the same query, hitting SQL Server, for the same data, over and over.",
      "",
      "## Redis in two places",
      "",
      "Redis was doing two different jobs in this project, and conflating them is the usual mistake:",
      "",
      "- **Shopping baskets** live in Redis. They are high-churn, per-session data that changes on nearly every interaction, and they are not relational. A 30-day TTL suits them perfectly.",
      "- **API responses** are cached behind a custom `ActionFilterAttribute`, with a configurable TTL (90 seconds by default).",
      "",
      "## The cache attribute",
      "",
      "```csharp",
      "public override async Task OnActionExecutionAsync(",
      "    ActionExecutingContext context, ActionExecutionDelegate next)",
      "{",
      "    var key = CreateCacheKey(context.HttpContext.Request, PerUser);",
      "    var cache = context.HttpContext.RequestServices.GetRequiredService<ICacheService>();",
      "",
      "    var hit = await cache.GetAsync(key);",
      "    if (hit is not null)",
      "    {",
      "        context.Result = new ContentResult { Content = hit, ContentType = \"application/json\" };",
      "        return;                       // short-circuit: the action never runs",
      "    }",
      "",
      "    var executed = await next.Invoke();",
      "    // store the response for next time",
      "}",
      "```",
      "",
      "## Per-user isolation",
      "",
      "A single global cache entry for `GET /api/orders` would be a data leak: every customer would see everyone else's orders. The cache key therefore includes the caller's identity when `PerUser` is set:",
      "",
      "- `GET /api/products` → **global** key. The catalogue is identical for everyone.",
      "- `GET /api/orders` → **per-user** key. Each customer sees only their own.",
      "",
      "That single flag is the difference between a fast endpoint and a serious privacy bug.",
      "",
      "## Invalidation: prefixes, not exact keys",
      "",
      "Deleting one exact key does not work when a single edit changes a whole list. Keys are namespaced by prefix and invalidated as a group:",
      "",
      "```text",
      "products:all\        products:brand:3        products:type:7",
      "```",
      "",
      "Updating one product invalidates `products:*`, which is cheap and always correct. Precision here buys nothing and frequently buys staleness.",
      "",
      "## Why SHA-256 keys",
      "",
      "Raw query strings contain characters that are awkward in Redis keys and easy to get subtly wrong. Hashing the composed key with SHA-256 gives a fixed, safe, collision-resistant key and keeps user identifiers out of the keyspace.",
      "",
      "## The result",
      "",
      "Response times on the cached paths dropped from about 60 ms to about 15 ms — roughly a 75% reduction — and the effect grew the busier the endpoint became, because a warm cache serves every subsequent request.",
      "",
      "## What I would add next",
      "",
      "- Stampede protection: collapse concurrent misses onto a single database call.",
      "- Explicit cache versioning, so a deploy can invalidate everything by bumping a namespace rather than flushing the database.",
      "- Metrics on hit rate, so a silently ineffective cache cannot hide.",
    ].join("\n"),
  },
];